In [196]:
n1 = 100_000
#poparr = Array{Union{Int8, Int16},2}(undef, n1, 6)

poparr = zeros(Int16,n1,6)
println(Base.summarysize(poparr))

1200040


In [183]:
age_dist = [0.251, 0.271,   0.255,   0.184,   0.039]

5-element Array{Float64,1}:
 0.251
 0.271
 0.255
 0.184
 0.039

In [184]:
using Distributions
using IndexedTables
using CategoricalArrays

In [185]:
dcat = Categorical(age_dist)

DiscreteNonParametric{Int64,Float64,Base.OneTo{Int64},Array{Float64,1}}(
support: Base.OneTo(5)
p: [0.251, 0.271, 0.255, 0.184, 0.039]
)


In [214]:
poparr[:,1] = rand(dcat,n1);
poparr[:,3] = ones(n1);
@time sort!(poparr,dims=1);

  0.011201 seconds (7 allocations: 304 bytes)


In [202]:
@time [count.(poparr[:,1] .== i for i in 1:5)] ./ n1

  0.095655 seconds (76.17 k allocations: 4.905 MiB)


1-element Array{Array{Float64,1},1}:
 [0.25385, 0.2719, 0.25232, 0.18417, 0.03776]

In [191]:
println(typeof(poparr))
Base.summarysize(poparr)

Array{Int16,2}


1200040

In [215]:
n = 500_000
poptable = table(zeros(Int8,n),zeros(Int8,n),zeros(Int8,n),zeros(Int16,n),zeros(Int16,n),zeros(Int8,n),
    names=[:agegrp,:sick,:status,:tested,:isolated,:lag], pkey=[:agegrp,:sick,:status,:tested,:isolated,:lag]);

In [216]:
Base.summarysize(poptable)

4000854

In [217]:
select(poptable, 1) .= Int8.(rand(dcat,n));
select(poptable, 3) .= ones(Int8, n);

In [219]:
@time poptable = table(sort(poptable, :agegrp), pkey=[:agegrp,:sick,:status,:tested,:isolated,:lag])

  0.030394 seconds (500.14 k allocations: 26.711 MiB)


Table with 500000 rows, 6 columns:
agegrp  sick  status  tested  isolated  lag
───────────────────────────────────────────
1       0     1       0       0         0
1       0     1       0       0         0
1       0     1       0       0         0
1       0     1       0       0         0
1       0     1       0       0         0
1       0     1       0       0         0
1       0     1       0       0         0
1       0     1       0       0         0
1       0     1       0       0         0
1       0     1       0       0         0
1       0     1       0       0         0
1       0     1       0       0         0
⋮
5       0     1       0       0         0
5       0     1       0       0         0
5       0     1       0       0         0
5       0     1       0       0         0
5       0     1       0       0         0
5       0     1       0       0         0
5       0     1       0       0         0
5       0     1       0       0         0
5       0     1       0       0    

In [220]:
@time select(groupby(length, poptable, :agegrp), :length) ./ n

  0.000631 seconds (218 allocations: 8.953 KiB)


5-element Array{Float64,1}:
 0.25075
 0.270716
 0.255372
 0.184374
 0.038788

In [180]:
filter(r->r.agegrp == 5, poptable);