In [41]:
using BenchmarkTools
using Distributions

In [6]:
rs = rand(50)

50-element Vector{Float64}:
 0.33959611337026185
 0.8884829577297646
 0.3836183444461614
 0.06263498107906096
 0.19516408762220583
 0.42298413801378887
 0.19721024009085242
 0.9454048193662887
 0.7373093736451208
 0.1919988012490863
 0.04970234091614101
 0.033076423540270294
 0.40366457789193566
 ⋮
 0.05409739392305224
 0.8148807897618382
 0.6133895219991359
 0.036466318660509645
 0.2936774113594254
 0.581653448718388
 0.23583397567618536
 0.19172020179762694
 0.7870685403113349
 0.8491332768701467
 0.7734152780652828
 0.861183119622035

In [9]:
rand()

0.20553025015208992

In [8]:
catdist = Dict(:out=>[1,5,7], :pr=>[.1, .7, .2])

Dict{Symbol, Vector{T} where T} with 2 entries:
  :out => [1, 5, 7]
  :pr  => [0.1, 0.7, 0.2]

In [ ]:
function catsim(catdist, rands=[])
    if isempty(rands)
        return rand()
            
            

In [10]:
prs = catdist[:pr]

3-element Vector{Float64}:
 0.1
 0.7
 0.2

In [20]:
@btime append!([$prs[1]],[$prs[i] + $prs[i-1] for i = 2:length($prs)])

  101.929 ns (3 allocations: 240 bytes)


3-element Vector{Float64}:
 0.1
 0.7999999999999999
 0.8999999999999999

In [153]:
function categorical_sim(prs::Vector{Float64}, do_assert=true)
    do_assert && @assert isapprox(sum(prs), 1.0)
    x = rand()
    cumpr = 0.0
    i = 0
    for pr in prs
        cumpr += pr
        i += 1
        if x <= cumpr 
            break
        end
    end
    i
end

function categorical_sim(prs::Vector{Float64}, n::Int, do_assert=true)
    do_assert && @assert isapprox(sum(prs), 1.0)
    ret = Vector{Int}(undef, n)
    
    @inbounds for i in 1:n
        ret[i] = categorical_sim(prs, false)
    end
    ret
end
        
        
    

categorical_sim (generic function with 8 methods)

In [156]:
@btime categorical_sim($catdist[:pr], false);

  23.790 ns (0 allocations: 0 bytes)


In [154]:
categorical_sim(catdist[:pr])

2

In [155]:
@btime rand(Categorical(catdist[:pr]));

  203.290 ns (2 allocations: 144 bytes)


In [157]:
24/207

0.11594202898550725

In [104]:
typeof(Int[1,2,3])

Vector{Int64} (alias for Array{Int64, 1})

In [108]:
for l in eachindex([10,20])
    println(l)
end

1
2


In [148]:
@btime rand(Categorical($catdist[:pr]),2000);

  43.983 μs (7 allocations: 16.33 KiB)


In [149]:
@btime categorical_sim($catdist[:pr],2000);

  23.889 μs (1 allocation: 15.75 KiB)


In [150]:
@btime zeros(Int, 2000);

  891.600 ns (1 allocation: 15.75 KiB)


In [151]:
@btime Vector{Int}(undef, 2000);

  174.480 ns (1 allocation: 15.75 KiB)
